name: tugas_1_aplikasi_x
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  file_picker: ^8.3.2
  flutter:
    sdk: flutter
  flutter_web_plugins: # If a package specifically needs this structure for web
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/logo-white.png"
    - "assets/images/profile.png"
  fonts:
    - family: "Chirp"
      fonts:
        - asset: "assets/fonts/Chirp-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Chirp-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Chirp-Regular.ttf"
          weight: 100
        